using System;
using System.Collections.Generic;

namespace Xy.Pis.Domain
{
    public partial class vwBsItem
    {
        public int ID { get; set; }
        public short LsGroupType { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string LongDesc { get; set; }
        public string EngDesc { get; set; }
        public string WbCode { get; set; }
        public string PyCode { get; set; }
        public string StrokeCode { get; set; }
        public string OtherCode { get; set; }
        public int GroupMainId { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> GroupSubId { get; set; }
        public string GroupSubName { get; set; }
        public string Spec { get; set; }
        public int UnitInId { get; set; }
        public string UnitInName { get; set; }
        public decimal PriceIn { get; set; }
        public int UnitDiagId { get; set; }
        public string UnitDiagName { get; set; }
        public decimal PriceDiag { get; set; }
        public decimal AddPercent { get; set; }
        public short LsRpType { get; set; }
        public decimal Dosage { get; set; }
        public Nullable<int> UnitTakeId { get; set; }
        public string UnitTakeName { get; set; }
        public Nullable<int> FrequencyId { get; set; }
        public string FrequencyName { get; set; }
        public Nullable<int> UsageId { get; set; }
        public int FeeMzId { get; set; }
        public string FeeMzName { get; set; }
        public int FeeZyId { get; set; }
        public Nullable<int> MzUnitTotal { get; set; }
        public string FeeZyName { get; set; }
        public short LsGfType { get; set; }
        public Nullable<decimal> GfFixDisc { get; set; }
        public bool OptionPrice { get; set; }
        public decimal LimitTotalMz { get; set; }
        public decimal LimitTotalZy { get; set; }
        public int TypeGFXEId { get; set; }
        public string TypeGFXEName { get; set; }
        public bool IsSpecSum { get; set; }
        public bool IsNew { get; set; }
        public bool IsOnlyForSys { get; set; }
        public bool IsRpForbid { get; set; }
        public bool IsChildAdd { get; set; }
        public bool IsBedFee { get; set; }
        public bool IsOpsAdd { get; set; }
        public short LsfeeTurn { get; set; }
        public short LsAdviceType { get; set; }
        public Nullable<int> ExecLocId { get; set; }
        public string ExecLocName { get; set; }
        public Nullable<int> LISCode { get; set; }
        public string Memo { get; set; }
        public bool IsActive { get; set; }
        public string ChemName { get; set; }
        public Nullable<bool> IsRecipe { get; set; }
        public Nullable<bool> IsPoison { get; set; }
        public Nullable<bool> IsMental { get; set; }
        public Nullable<bool> IsExpen { get; set; }
        public Nullable<bool> IsSelf { get; set; }
        public Nullable<int> ProArea { get; set; }
        public Nullable<int> AheadAlert { get; set; }
        public Nullable<decimal> UnderLineKc { get; set; }
        public Nullable<decimal> UperLineKc { get; set; }
        public Nullable<decimal> NormalLineKc { get; set; }
        public Nullable<int> FormId { get; set; }
        public string DrugFormName { get; set; }
        public Nullable<int> ManuId { get; set; }
        public string ManufacturerName { get; set; }
        public string PassNo { get; set; }
        public string AreaKc { get; set; }
        public Nullable<short> LsImport { get; set; }
        public Nullable<bool> IsInject { get; set; }
        public Nullable<bool> IsSpecial { get; set; }
        public Nullable<int> HouseId { get; set; }
        public string HouseName { get; set; }
        public Nullable<int> RoomIdOut { get; set; }
        public string RoomNameOut { get; set; }
        public Nullable<int> RoomIdIn { get; set; }
        public string RoomInOut { get; set; }
        public Nullable<int> UnitKc { get; set; }
        public Nullable<decimal> RetailPriceKc { get; set; }
        public Nullable<decimal> StockPriceKc { get; set; }
        public Nullable<bool> IsBid { get; set; }
        public Nullable<bool> IsLocDrug { get; set; }
        public Nullable<int> CompId { get; set; }
        public string CompanyName { get; set; }
        public Nullable<bool> IsBatch { get; set; }
        public Nullable<bool> IsSave { get; set; }
        public int PatTypeId { get; set; }
        public string PatTypeName { get; set; }
        public int DiscDiag { get; set; }
        public int DiscIn { get; set; }
        public Nullable<int> InvInItemId { get; set; }
        public string InvInItemName { get; set; }
        public Nullable<int> InvMzItemId { get; set; }
        public string InvMzItemName { get; set; }
        public int LimitGroupId { get; set; }
        public string ZyGroupName { get; set; }
        public int LimitFeeMz { get; set; }
        public int LimitFeeZy { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string LocationName { get; set; }
        public int FeeHsMzId { get; set; }
        public int FeeHsZyId { get; set; }
        public string FeeHsZyName { get; set; }
        public string FeeHsMzName { get; set; }
        public decimal LocationDosage { get; set; }
        public Nullable<int> LocationUnitTakeId { get; set; }
        public string LocationUnitTakeName { get; set; }
        public Nullable<int> LocationFrequencyId { get; set; }
        public string LocationFrequencyName { get; set; }
        public Nullable<int> LocationUsageId { get; set; }
        public string LocationUsageName { get; set; }
        public string UsageName { get; set; }
        public string UnitKcName { get; set; }
        public string TallyGroupName { get; set; }
        public Nullable<bool> LocationIsLocDrug { get; set; }
        public int TallyTypeId { get; set; }
        public int TallyGroupId { get; set; }
        public short IconIndex { get; set; }
        public Nullable<bool> IsInoculate { get; set; }
        public string F1 { get; set; }
        public string F2 { get; set; }
        public string F3 { get; set; }
        public string F4 { get; set; }
        public Nullable<short> OrderBy { get; set; }
        public Nullable<int> DrugID { get; set; }
    }
}
