using System;
using System.Collections.Generic;

namespace Xy.Pis.Domain
{
    public partial class VwInHosInfoAndInHosInfoRenew
    {
        public int ID { get; set; }
        public string HospNo { get; set; }
        public string InPatNo { get; set; }
        public string CardNo { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<short> LsMarriage { get; set; }
        public string BloodGroup { get; set; }
        public Nullable<System.DateTime> InTime { get; set; }
        public int NTime { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string Residence { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public bool IsOversea { get; set; }
        public Nullable<System.DateTime> PassTime { get; set; }
        public string IdCardNo { get; set; }
        public string Company { get; set; }
        public string Occupation { get; set; }
        public Nullable<int> WorktypeId { get; set; }
        public int PatTypeId { get; set; }
        public Nullable<int> CertificateId { get; set; }
        public Nullable<short> LsInType { get; set; }
        public Nullable<short> LsInWay { get; set; }
        public Nullable<short> LsInIllness { get; set; }
        public Nullable<int> DocMz { get; set; }
        public Nullable<int> DoctorId { get; set; }
        public int LocIn { get; set; }
        public Nullable<int> LocationId { get; set; }
        public bool IsYbMt { get; set; }
        public string YbRegNo { get; set; }
        public Nullable<decimal> ArrearAmount { get; set; }
        public string AgeDay { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string PhoneHome { get; set; }
        public string AddressHome { get; set; }
        public string PostCodeHome { get; set; }
        public string AreaCodeHome { get; set; }
        public string PhoneWork { get; set; }
        public string AddressWork { get; set; }
        public string PostCodeWork { get; set; }
        public string AreaCodeWork { get; set; }
        public string LinkmanName { get; set; }
        public Nullable<int> RelationId { get; set; }
        public string LinkmanPhone { get; set; }
        public string LinkmanAddress { get; set; }
        public string LinkmanPost { get; set; }
        public string LinkmanArea { get; set; }
        public short LsInStatus { get; set; }
        public string Status { get; set; }
        public System.DateTime OperTime { get; set; }
        public int OperID { get; set; }
        public string MedicareNo { get; set; }
        public string AccountNo { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> AreaId { get; set; }
        public string Native { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<short> Circumference { get; set; }
        public Nullable<short> Waistline { get; set; }
        public Nullable<short> Sternline { get; set; }
        public int PatID { get; set; }
        public Nullable<System.DateTime> OutTime { get; set; }
        public bool IsEndChg { get; set; }
        public Nullable<int> EndChgOperID { get; set; }
        public Nullable<System.DateTime> EndchgoperTime { get; set; }
        public Nullable<int> NationId { get; set; }
        public Nullable<int> ProvinceId { get; set; }
        public string Sensitive { get; set; }
        public Nullable<int> FamilyId { get; set; }
        public Nullable<bool> isHouseMaster { get; set; }
        public Nullable<int> RelaMasterId { get; set; }
        public Nullable<short> LsCensus { get; set; }
        public Nullable<int> CommitteeId { get; set; }
        public Nullable<int> PoliceStationId { get; set; }
        public Nullable<int> LevelId { get; set; }
        public Nullable<short> LsSport { get; set; }
        public Nullable<short> LsSportTime { get; set; }
        public Nullable<short> LsSportType { get; set; }
        public Nullable<short> LsBitHabit { get; set; }
        public Nullable<short> SleepHour { get; set; }
        public Nullable<short> LsSleepTrouble { get; set; }
        public string SmokeHistory { get; set; }
        public string DrinkHistory { get; set; }
        public string OtherHabit { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string InActiveReason { get; set; }
        public Nullable<System.DateTime> InActiveTime { get; set; }
        public Nullable<int> InActiveOperID { get; set; }
        public Nullable<short> IconIndex { get; set; }
        public string HealthCardNo { get; set; }
        public Nullable<short> LsHealthGrade { get; set; }
        public Nullable<int> HouseholdRegisterCityId { get; set; }
        public Nullable<int> HouseholdRegisterCountyId { get; set; }
        public Nullable<int> HouseholdRegisterAddCountyId { get; set; }
        public Nullable<int> HouseholdRegisterProvinceId { get; set; }
        public Nullable<int> DomicileStreetTownId { get; set; }
        public string HouseholdRegisterAddress { get; set; }
        public string AgeString { get; set; }
        public string PyCode { get; set; }
        public Nullable<decimal> BedAmount { get; set; }
        public Nullable<decimal> NursingCost { get; set; }
        public int HosRenewId { get; set; }
        public Nullable<int> HospId { get; set; }
        public Nullable<int> OperRenewId { get; set; }
        public Nullable<System.DateTime> OperRenewTime { get; set; }
        public Nullable<int> Frequency { get; set; }
        public string OutBedAddress { get; set; }
        public Nullable<int> BedId { get; set; }
        public Nullable<int> NursingGradeId { get; set; }
        public string FirstLinkmanName { get; set; }
        public Nullable<int> FirstRelationId { get; set; }
        public string FirstLinkmanIdCard { get; set; }
        public string FirstLinkManWorkUnit { get; set; }
        public string FirstLinkmanUnitAddress { get; set; }
        public string FirstLinkmanFamilyAddress { get; set; }
        public string FirstLinkmanFamilyPhone { get; set; }
        public string FirstLinkmanPhone { get; set; }
        public string SecondLinkmanName { get; set; }
        public Nullable<int> SecondRelationId { get; set; }
        public string SecondLinkmanIdCard { get; set; }
        public string SecondLinkManWorkUnit { get; set; }
        public string SecondLinkmanUnitAddress { get; set; }
        public string SecondLinkmanFamilyAddress { get; set; }
        public string SecondLinkmanFamilyPhone { get; set; }
        public string SecondLinkmanPhone { get; set; }
        public Nullable<int> BedYearTypeId { get; set; }
        public Nullable<short> LsOutManagementType { get; set; }
        public Nullable<int> AddRatioId { get; set; }
        public Nullable<short> LsEconomicSource { get; set; }
        public Nullable<int> MealTypeId { get; set; }
        public Nullable<int> ServiceChargeId { get; set; }
        public Nullable<System.DateTime> AgreementBeginDate { get; set; }
        public Nullable<System.DateTime> AgreementEndDate { get; set; }
        public bool IsCheckInCharge { get; set; }
        public Nullable<decimal> OneTimeFacilityFee { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> ServiceChargeAmount { get; set; }
    }
}
